blank_issues_enabled: false
contact_links:
  - name: Auth0 Community
    url: https://community.auth0.com
    about: Discuss this SDK in the Auth0 Community forums
  - name: SDK API Documentation
    url: https://auth0.github.io/auth0.net/
    about: Read the API documentation for this SDK 
