using Auth0.ManagementApi;

namespace Auth0.ManagementApi.Users;

public partial interface IIdentitiesClient
{
    /// <summary>
    /// Link two user accounts together forming a primary and secondary relationship. On successful linking, the endpoint returns the new array of the primary account identities.
    ///
    /// Note: There are two ways of invoking the endpoint:
    ///
    /// <list type="bullet">
    ///   <item><description>With the authenticated primary account's JWT in the Authorization header, which has the <c>update:current_user_identities</c> scope:
    ///     <code>
    ///       POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
    ///       Authorization: "Bearer PRIMARY_ACCOUNT_JWT"
    ///       {
    ///         "link_with": "SECONDARY_ACCOUNT_JWT"
    ///       }
    ///     </code>
    ///     In this case, only the <c>link_with</c> param is required in the body, which also contains the JWT obtained upon the secondary account's authentication.
    ///   </description></item>
    ///   <item><description>With a token generated by the API V2 containing the <c>update:users</c> scope:
    ///     <code>
    ///     POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
    ///     Authorization: "Bearer YOUR_API_V2_TOKEN"
    ///     {
    ///       "provider": "SECONDARY_ACCOUNT_PROVIDER",
    ///       "connection_id": "SECONDARY_ACCOUNT_CONNECTION_ID(OPTIONAL)",
    ///       "user_id": "SECONDARY_ACCOUNT_USER_ID"
    ///     }
    ///     </code>
    ///     In this case you need to send <c>provider</c> and <c>user_id</c> in the body. Optionally you can also send the <c>connection_id</c> param which is suitable for identifying a particular database connection for the 'auth0' provider.
    ///   </description></item>
    /// </list>
    /// </summary>
    WithRawResponseTask<IEnumerable<UserIdentity>> LinkAsync(
        string id,
        LinkUserIdentityRequestContent request,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Unlink a specific secondary account from a target user. This action requires the ID of both the target user and the secondary account.
    ///
    /// Unlinking the secondary account removes it from the identities array of the target user and creates a new standalone profile for the secondary account. To learn more, review <see href="https://auth0.com/docs/manage-users/user-accounts/user-account-linking/unlink-user-accounts">Unlink User Accounts</see>.
    /// </summary>
    WithRawResponseTask<IEnumerable<DeleteUserIdentityResponseContentItem>> DeleteAsync(
        string id,
        UserIdentityProviderEnum provider,
        string userId,
        RequestOptions? options = null,
        CancellationToken cancellationToken = default
    );
}
