using System.Text.Json;
using System.Text.Json.Serialization;
using Auth0.ManagementApi.Core;

namespace Auth0.ManagementApi;

/// <summary>
/// The successfully created authentication method.
/// </summary>
[Serializable]
public record UpdateUserAuthenticationMethodResponseContent : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// The ID of the newly created authentication method (automatically generated by the application)
    /// </summary>
    [Optional]
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public required CreatedAuthenticationMethodTypeEnum Type { get; set; }

    /// <summary>
    /// A human-readable label to identify the authentication method.
    /// </summary>
    [Optional]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Base32 encoded secret for TOTP generation
    /// </summary>
    [Optional]
    [JsonPropertyName("totp_secret")]
    public string? TotpSecret { get; set; }

    /// <summary>
    /// Applies to phone authentication methods only. The destination phone number used to send verification codes via text and voice.
    /// </summary>
    [Optional]
    [JsonPropertyName("phone_number")]
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// Applies to email authentication methods only. The email address used to send verification messages.
    /// </summary>
    [Optional]
    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [Optional]
    [JsonPropertyName("authentication_methods")]
    public IEnumerable<UserAuthenticationMethodProperties>? AuthenticationMethods { get; set; }

    [Optional]
    [JsonPropertyName("preferred_authentication_method")]
    public PreferredAuthenticationMethodEnum? PreferredAuthenticationMethod { get; set; }

    /// <summary>
    /// Applies to webauthn authentication methods only. The id of the credential.
    /// </summary>
    [Optional]
    [JsonPropertyName("key_id")]
    public string? KeyId { get; set; }

    /// <summary>
    /// Applies to webauthn authentication methods only. The public key.
    /// </summary>
    [Optional]
    [JsonPropertyName("public_key")]
    public string? PublicKey { get; set; }

    /// <summary>
    /// Applies to passkey authentication methods only. Authenticator Attestation Globally Unique Identifier.
    /// </summary>
    [Optional]
    [JsonPropertyName("aaguid")]
    public string? Aaguid { get; set; }

    /// <summary>
    /// Applies to webauthn authentication methods only. The relying party identifier.
    /// </summary>
    [Optional]
    [JsonPropertyName("relying_party_identifier")]
    public string? RelyingPartyIdentifier { get; set; }

    /// <summary>
    /// Authentication method creation date
    /// </summary>
    [Optional]
    [JsonPropertyName("created_at")]
    public DateTime? CreatedAt { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
