name: RL-Secure Workflow
run-name: rl-scanner

on:
  workflow_call:
    inputs:
      project-path:
        type: string        
        required: true
      artifact-name:
        type: string
        required: true
    secrets:
      RLSECURE_LICENSE:
        required: true
      RLSECURE_SITE_KEY:
        required: true
      SIGNAL_HANDLER_TOKEN:
        required: true
      SIGNAL_HANDLER_DOMAIN:
        required: true
      PRODSEC_TOOLS_USER:
        required: true
      PRODSEC_TOOLS_TOKEN:
        required: true
      PRODSEC_TOOLS_ARN:
        required: true
      PRODSEC_PYTHON_TOOLS_REPO:
        required: true

jobs:
  rl-scanner:
    name: Run Reversing Labs scanner
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest
    outputs:
      scan-status: ${{ steps.rl-scan-conclusion.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x

      - name: Create NuGet packages
        shell: pwsh
        env:
          PROJECT_PATH: ${{ inputs.project-path }}
          NUGET_OUTPUT: ${{ github.workspace }}/nuget
        run: |
          dotnet pack $env:PROJECT_PATH --configuration Release --output $env:NUGET_OUTPUT

      - name: Create tgz build artifact
        env:
          ARTIFACT_NAME: ${{ inputs.artifact-name }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          tar -czvf "$WORKSPACE/$ARTIFACT_NAME" "$WORKSPACE/nuget"
      
      - id: get_version
        uses: ./.github/actions/get-version

      - name: Run RL Scanner
        id: rl-scan-conclusion
        uses: auth0/devsecops-tooling/.github/actions/rl-scan@main
        with:
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: ${{ github.workspace }}/${{ inputs.artifact-name }}
          version: "${{ steps.get_version.outputs.version }}"
          RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          SIGNAL_HANDLER_DOMAIN: ${{ secrets.SIGNAL_HANDLER_DOMAIN }}
          PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}
          PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
          PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
          PRODSEC_PYTHON_TOOLS_REPO: ${{ secrets.PRODSEC_PYTHON_TOOLS_REPO }}

      - name: Output scan result
        run: echo "scan-status=${{ steps.rl-scan-conclusion.outcome }}" >> $GITHUB_ENV